import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request) {
  try {
    const { name, email, message } = await request.json();

    if (!name || !email || !message) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    // MODERN & PREMIUM EMAIL TEMPLATE WITH BOLD LABELS
    const data = await resend.emails.send({
      from: "Portfolio Contact <onboarding@resend.dev>", // Domain verify hone ke baad apna domain lagana
      to: "diwakarpandey410@gmail.com",
      subject: `🚀 New Portfolio Message from ${name}`,
      replyTo: email,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>New Message</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f9fafb; margin: 0; padding: 20px; color: #1f2937; }
              .container { max-width: 600px; background: #ffffff; margin: 0 auto; border-radius: 16px; border: 1px solid #e5e7eb; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05); }
              .header { background: #111827; padding: 32px 24px; text-align: center; }
              .header h1 { color: #ffffff; margin: 0; font-size: 22px; font-weight: 700; letter-spacing: -0.025em; }
              .header p { color: #9ca3af; margin: 8px 0 0 0; font-size: 14px; }
              .content { padding: 32px 24px; }
              .field-group { margin-bottom: 24px; border-bottom: 1px solid #f3f4f6; padding-bottom: 16px; }
              .field-group:last-child { margin-bottom: 0; border-bottom: none; padding-bottom: 0; }
              
              /* LABELS BOLD STYLE */
              .label { font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #111827; font-weight: 800; margin-bottom: 3px; display: block; }
              
              .value { font-size: 16px; color: #374151; font-weight: 500; margin: 0; }
              .message-box { background: #f3f4f6; padding: 16px; border-radius: 12px; font-size: 15px; color: #1f2937; line-height: 1.6; white-space: pre-wrap; margin-top: 6px; border-left: 4px solid #111827; }
              .footer { background: #f9fafb; padding: 20px 24px; text-align: center; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
              .btn { display: inline-block; background: #111827; color: #ffffff !important; text-decoration: none; padding: 12px 20px; font-size: 14px; font-weight: 600; border-radius: 8px; margin-top: 12px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>📬 New Contact Form Submission</h1>
                <p>Sent from your personal portfolio website</p>
              </div>
              <div class="content">
                <div class="field-group">
                  <span class="label">SENDER NAME:</span>
                  <p class="value">${name}</p>
                </div>
                
                <div class="field-group">
                  <span class="label">EMAIL ADDRESS:</span>
                  <p class="value">
                    <a href="mailto:${email}" style="color: #2563eb; text-decoration: none; font-weight: 600;">${email}</a>
                  </p>
                </div>
                
                <div class="field-group">
                  <span class="label">MESSAGE:</span>
                  <div class="message-box">${message.replace(/\n/g, "<br>")}</div>
                </div>
                
                <div style="text-align: center; margin-top: 32px;">
                  <a href="mailto:${email}" class="btn">Reply Directly</a>
                </div>
              </div>
              <div class="footer">
                <p>This email was automatically generated by your Next.js application.</p>
              </div>
            </div>
          </body>
        </html>
      `,
    });

    return NextResponse.json({ success: true, data });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}