import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

const geistMono = Montserrat({
  variable: "--font-mont",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${geistMono.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-light font-sans">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
